name: docs
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: pip install mkdocs-material
      #      - name: Set up git credentials
      #        uses: oleksiyrudenko/gha-git-credentials@v2-latest
      #        with:
      #          global: true
      #          token: ${{ secrets.USER_TOKEN }}
      - name: Deploy docs
        run: mkdocs build -d ./dist
      - name: Deploy to staticinator
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          tar -czvf "./archive.tar.gz" -C "./dist" .
          curl -F "file=@./archive.tar.gz" -H "Token: $TOKEN" -H "Target-Host: $HOST" "https://deploy.enjarai.dev/update" -v
          
